// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateEventsParams struct {
	TimelineID       pgtype.UUID `json:"timeline_id"`
	Title            string      `json:"title"`
	CardTitle        string      `json:"card_title"`
	CardSubtitle     pgtype.Text `json:"card_subtitle"`
	CardDetailedText pgtype.Text `json:"card_detailed_text"`
	MediaName        pgtype.Text `json:"media_name"`
	MediaType        pgtype.Text `json:"media_type"`
	MediaUrl         pgtype.Text `json:"media_url"`
	Position         pgtype.Int4 `json:"position"`
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events e
USING timelines t
WHERE e.id = $1
  AND e.timeline_id = t.id
  AND t.user_id = $2
`

type DeleteEventParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteEvent(ctx context.Context, arg DeleteEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEventsByTimelineId = `-- name: DeleteEventsByTimelineId :execrows
DELETE FROM events e
USING timelines t
WHERE e.timeline_id = t.id
  AND e.timeline_id = $1
  AND t.user_id = $2
`

type DeleteEventsByTimelineIdParams struct {
	TimelineID pgtype.UUID `json:"timeline_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteEventsByTimelineId(ctx context.Context, arg DeleteEventsByTimelineIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEventsByTimelineId, arg.TimelineID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEventsByTimelineId = `-- name: GetEventsByTimelineId :many
SELECT id, timeline_id, title, card_title, card_subtitle, card_detailed_text, created_at, updated_at, media_name, media_type, media_url, position
FROM events
WHERE timeline_id = $1
ORDER BY position ASC
`

func (q *Queries) GetEventsByTimelineId(ctx context.Context, timelineID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByTimelineId, timelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TimelineID,
			&i.Title,
			&i.CardTitle,
			&i.CardSubtitle,
			&i.CardDetailedText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MediaName,
			&i.MediaType,
			&i.MediaUrl,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxPositionByTimelineId = `-- name: GetMaxPositionByTimelineId :one
SELECT COALESCE(MAX(position), 0) 
FROM events
WHERE timeline_id = $1
`

func (q *Queries) GetMaxPositionByTimelineId(ctx context.Context, timelineID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxPositionByTimelineId, timelineID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
